# Generated by Django 3.0.5 on 2020-05-22 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis_categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='apis_categorias.Categoria')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productosuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Precios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioinsumo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioespecial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_precios', to='apis_productos.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='Productos/Fotos')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='Productos/Fotos')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='Productos/Fotos')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='Productos/Fotos')),
                ('estado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_fotos', to='apis_productos.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteina', models.FloatField()),
                ('carbohidrato', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='apis_productos.Productos')),
            ],
        ),
    ]
