# Generated by Django 3.0.2 on 2020-05-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_productos', '0002_auto_20200524_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_fotos',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='producto_fotos',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='Productos/Fotos'),
        ),
        migrations.AddField(
            model_name='producto_fotos',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='Productos/Fotos'),
        ),
        migrations.AddField(
            model_name='producto_fotos',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='Productos/Fotos'),
        ),
    ]
