# Generated by Django 3.0.5 on 2020-05-13 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Despachos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cordenadamapa1', models.IntegerField()),
                ('cordenadamapa2', models.IntegerField()),
                ('fechahoradespacho', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroped', models.IntegerField()),
                ('pedidofecha', models.DateTimeField()),
                ('completo', models.BooleanField(default=True)),
                ('numerodoc', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('ruc', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Personas/Fotos')),
                ('estado', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='usuarios.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('promociondesde', models.DateTimeField(blank=True, null=True)),
                ('promocionhasta', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('web', models.CharField(blank=True, max_length=300, null=True)),
                ('ruc', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(choices=[(0, 'Boleta'), (1, 'Factura'), (2, 'Ticket')], default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjetanombre', models.CharField(blank=True, max_length=300, null=True)),
                ('tarjetanumero', models.CharField(blank=True, max_length=30, null=True)),
                ('tarjetacvv', models.IntegerField(blank=True, null=True)),
                ('tarjetaexp', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Personas')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion_Detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('porcentajedescuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Productos')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Promociones')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Proveedor'),
        ),
        migrations.AddField(
            model_name='productos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Producto_Precios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioinsumo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioespecial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_precios', to='usuarios.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='Productos/Fotos')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='Productos/Fotos')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='Productos/Fotos')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='Productos/Fotos')),
                ('estado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_fotos', to='usuarios.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_Detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precioelegido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Productos')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='usuarios.Personas'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='usuarios.Promociones'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tipodocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.TipoDocumento'),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjetanombre', models.CharField(blank=True, max_length=300, null=True)),
                ('tarjetanumero', models.CharField(blank=True, max_length=30, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteina', models.FloatField()),
                ('carbohidrato', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='usuarios.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadevolucion', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Personas')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fechahoradespachoentrega', models.DateTimeField()),
                ('cordenadaubicacion1', models.IntegerField()),
                ('cordenadaubicacion2', models.IntegerField()),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='Despachos/Fotos')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='Despachos/Fotos')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='Despachos/Fotos')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='Despachos/Fotos')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Despachos')),
            ],
        ),
        migrations.AddField(
            model_name='despachos',
            name='despachador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Personas'),
        ),
        migrations.AddField(
            model_name='despachos',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Pedidos'),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estrellas', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Personas')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidofecha', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Personas')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Promociones')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoDetalleSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.CarritoSession')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Productos')),
            ],
        ),
    ]
